baseURL = 'https://code.astrodata.nyc/'
languageCode = 'en-us'
title = 'An Astronomical Software Development Crash Course'

theme = "code"

[params]
venue = 'Center for Computational Astrophysics'
venueLink = 'https://www.simonsfoundation.org/flatiron/center-for-computational-astrophysics/'
location = 'New York, NY'
dates = 'May 16–20, 2022'
