baseURL = 'https://code.astrodata.nyc/'
languageCode = 'en-us'
title = 'Astronomical Software Development'

theme = "code"

[params]
location = 'Center for Computational Astrophysics, New York, NY'
dates = 'May 16–20, 2022'
