name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install hugo
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.89.0/hugo_extended_0.89.0_Linux-64bit.tar.gz
          tar -xvf hugo_extended_0.89.0_Linux-64bit.tar.gz
          rm hugo_extended_0.89.0_Linux-64bit.tar.gz
          ./hugo version
      - name: Build the site
        run: |
          ./hugo
          rm hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: code.astrodata.nyc
          force_orphan: true