name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.89.0'
          extended: true

      - name: Build the site
        run: |
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: code.astrodata.nyc
          force_orphan: true
